### ISSUE TITLE
Different style of collection serialization

### ISSUE THREAD

**Issue by okuramasafumi** [okuramasafumi/alba#107]
Alba currently serializes a collection into an Array:

```ruby
class User
  attr_reader :id

  def initialize(id)
    @id = id
  end
end

user1 = User.new(1)
user2 = User.new(2)

class UserResource
  include Alba::Resource
  attributes :id
end

UserResource.new([user1, user2]).serializable_hash
# => [{:id=>1}, {:id=>2}]
```

However, sometimes we want to serialize a collection into a Hash with a certain key. The interface will be like:

```ruby
class UserResource
  include Alba::Resource

  collection_key :id

  attributes :id
end
```

With `collection_key`, we can specify the key for the Hash. Now `UserResource` will serialize a collection differently.

```ruby
UserResource.new([user1, user2]).serializable_hash
# => {'1' => {:id=>1}, '2' =>  {:id=>2}}
```

This way, Alba provides more flexible way to deal with collections.

**Comment by heka1024** [comment]
Was there an issue about PR#119? I' think that PR should close this.

**Comment by okuramasafumi** [comment]
Oh I closed that because `to_h` with block is not supported in Ruby 2.5 and 2.6, and at that time Alba supported them.
Now that Alba supports Ruby 2.7 and above that implements `to_h` with block, it's worth salvaging the code.
