### ISSUE TITLE
Be able to plugin a custom inflector

### ISSUE THREAD

**Issue by wuarmin** [okuramasafumi/alba#123]
Hey,

great gem!

## Is your feature request related to a problem? Please describe.
If you need key transformation, but there's no active_support around, you have to create workarounds to achieve key-transformation. It would be great, if we could add the possibility to plugin a custom **inflector**. For example, I have a "hanami-api-dry-project" and there the [dry-inflector](https://github.com/dry-rb/dry-inflector) is around. And I don't want to add the active_support-dependency.

## Describe the solution you'd like
One solution might be, to be able to plugin a custom **inflector**, which has to provide the supported api (#camelize, #dasherize): 
```ruby
Alba.inflector = Dry::Inflector.new # the default one should stay ActiveSupport::Inflector
```

Are you interested in this feature?

Best regards and thank you

**Comment by okuramasafumi** [comment]
Hi, thanks for the proposal! It would be nice if we had a swappable backend for key transformation.
Are you interested in implementing this feature by yourself?

**Comment by wuarmin** [comment]
Hi,
great! Yes of course I can do that.

**Comment by okuramasafumi** [comment]
@wuarmin Cool! Looking forward to your Pull Request!
