### ISSUE TITLE
How to migrate from Netflix/FastJsonApi to Alba?

### ISSUE THREAD

**Issue by pedrofurtado** [okuramasafumi/alba#144]
@okuramasafumi Hi! 👋 

Thanks for this awesome gem 👍 🏆 

How to migrate from Netflix/FastJsonApi to Alba?

**Comment by okuramasafumi** [comment]
Hi, `fast_jsonapi` is a gem for JSON:API spec, which Alba currently doesn't support.
I'm planning to support it in the future release of Alba (see #104), so after implementing that we can write a document for migrating from `fast_jsonapi` or other JSON:API compatible gems to Alba.
