### ISSUE TITLE
possible to refactor this attribute to use a symbol ?

### ISSUE THREAD

**Issue by mjobin-mdsol** [okuramasafumi/alba#152]
works fine, I'd like to write it to be easier to read it

current code

```ruby
  attribute :overridden_at, if: proc { |resource|
                                  resource.respond_to?(:overridden_at) && resource.overridden_at.present?
                                } do |resource|
    resource.overridden_at.iso8601(3)
  end
```

## Describe the solution you'd like
We need to call `respond_to?` because the attribute comes from a joined relation, which is not always present when calling this serializer.
then we don't want to include the field in the json when its nil, thus using the `if: proc` 

if we could write it such as

```ruby
attribute :overridden_at, if: :has_overriden_at? do |resource|
  resource.overridden_at.iso8601(3)
end

def has_overriden_at?(resource)
  resource.respond_to?(:overridden_at) && resource.overridden_at.present?
end

```
is this already possible?

**Comment by okuramasafumi** [comment]
Hi, using symbol as a method name in `if` option is not supported right now. It's good for readability so I think Alba should support it.
