### ISSUE TITLE
AR::Relation has updated their cache_key_with_version when collection is updated

### ISSUE THREAD

**Issue by saiqulhaq** [okuramasafumi/alba#154]
Have you take a look at this PR https://github.com/wbotelhos/rails/commit/1d2a08ee77c03a45fbcd6af10795e305aad6eb9e ?
so this statement (https://github.com/okuramasafumi/alba/blame/main/README.md#L672) is it still relevant?
does caching feature work?

**Comment by okuramasafumi** [comment]
You mean https://github.com/rails/rails/pull/41789 ?
This isn't shipped yet, so after it's released I'll reconsider.

**Comment by saiqulhaq** [comment]
ok thanks
