### ISSUE TITLE
Where to keep Configurations?

### ISSUE THREAD

**Issue by sagarkt** [okuramasafumi/alba#162]
I am going to try this gem. As a suggestion, here it is not clear where to add the configurations. I am currently moving ahead with creation of the initialize. Maybe docs can be improved further to guide this.

https://github.com/okuramasafumi/alba/blob/0c6f24babd16ada6d45f658747dbbbba5fe1e946/README.md?plain=1#L100

**Comment by okuramasafumi** [comment]
In Rails application, you can have your configurations in `config/initializers`.
I didn't mention it in README because it's so obvious to Rails developers. In Sinatra or Hanami, the config location is different but I don't want to cover them all in README. Patches are welcome!
