### ISSUE TITLE
Is it ok to add rake command for rails installation ?

### ISSUE THREAD

**Issue by Samemura** [okuramasafumi/alba#169]
## Is your feature request related to a problem? Please describe.
Feature request.
I am using Alba with Rails then thought will be happy if we have rake command to install to rails.

## Describe the solution you'd like
Add rake command to install alba setting(like initializer), alba resource file template.
Or it could be done by rails generate command.

**Comment by okuramasafumi** [comment]
What do you think should Alba provide as an install command? Obviously an initializer file, but what else?

**Comment by okuramasafumi** [comment]
@Samemura I'm closing this issue since "installing" Alba to Rails is just writing a few lines of initializer so I think we don't need Rake task.
Pull Request is welcome!
