### ISSUE TITLE
`root_key_for_collection` DSL

### ISSUE THREAD

**Issue by okuramasafumi** [okuramasafumi/alba#195]
## Is your feature request related to a problem? Please describe.

When setting a root key only for collection, it looks like this:

```ruby
root_key :_, :foos
```

Here, the first `:_` looks ugly but required.

## Describe the solution you'd like

```ruby
root_key_for_collection :foos
```

## Describe alternatives you've considered

None.

## Additional context

This is the real problem in my client work :)

**Comment by heka1024** [comment]
Hello, @okuramasafumi. I would like to contribute to this. Can I work on this issue?

**Comment by okuramasafumi** [comment]
Hi @heka1024 absolutely, go ahead! If you need help, please let me know.

**Comment by alexcastrodev** [comment]
> Hi [@heka1024](https://github.com/heka1024) absolutely, go ahead! If you need help, please let me know.

is it possible to root_key_for_collection be the same of root_key ?

**Comment by okuramasafumi** [comment]
Hi @alexcastrodev , I'm planning to refine root_key related features a bit, including `root_key_for_collection`. 

Currently, `root_key :user` means there's no root key for user collections. This doesn't make much sense to me. I'd like to change its meaning to have `:user` as root key for both single resources and collections.
That said, currently you need to do something like `root_key :user, :user` to have the same key for both.

**Comment by alexcastrodev** [comment]
> Hi [@alexcastrodev](https://github.com/alexcastrodev) , I'm planning to refine root_key related features a bit, including `root_key_for_collection`.
> 
> Currently, `root_key :user` means there's no root key for user collections. This doesn't make much sense to me. I'd like to change its meaning to have `:user` as root key for both single resources and collections. That said, currently you need to do something like `root_key :user, :user` to have the same key for both.

Only using `root_key_for_collection :user` i dont need to set `root_key :user, :users`
Is it a side effect? lol
