### ISSUE TITLE
Rails integration

### ISSUE THREAD

**Issue by kapso** [okuramasafumi/alba#205]
In a rails project, where should we create `*Resource` objects?

We are existing users of `jsonapi-serializer` in our Rails v7 project, and create `*Serializer` objects in `app/serializers`. Is that the same for Alba resources?

Also, is this path configurable? Asking this coz what if we wanna use both Alba and `jsonapi-serializer` in our Rails project.

**Comment by okuramasafumi** [comment]
@kapso Actually you can put any class including Alba's resource class to `app/serializers` folder. Note that you must set a file name corresponding to the class name. For example, `UserResource` class must be put as `app/serializers/user_resource.rb` or `app/resources/user_resource.rb` or whatever folder you want.

You should be able to mix Alba and other libraries without any problem.

**Comment by kapso** [comment]
@okuramasafumi thanks for the quick response, and this gem.
