### ISSUE TITLE
Inconsistentcy between `#serialize` (aka `#to_json`) and `#serializable_hash` (aka `#as_json`)

### ISSUE THREAD

**Issue by jcmfernandes** [okuramasafumi/alba#207]
Hi! First of all, thank you for putting this project together! :trophy: 

I'm working on a Rails project, and I stumbled across the fact that `#as_json` doesn't consider root keys. This stops me me from writing

```rb
render json: UserSerializer.new(user), status: :ok
```

in my controllers. This forces me to render a text/raw payload and take care of the content-type header. More importantly, it breaks the expectation that `JSON.generate(obj.as_json) == obj.to_json`.

Is this something by design? Or may I attempt to change it?

**Comment by okuramasafumi** [comment]
@jcmfernandes Alba doesn't implement `as_json` itself.
Rails expects the object given to `render json:` responds to `to_json`. It's documented https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-json
It's possible to implement `as_json` to get `JSON.generate(obj.as_json) == obj.to_json`.

**Comment by okuramasafumi** [comment]
@jcmfernandes Do you still have a problem? If so, I'd like to help you resolve it. Otherwise, I'll close it within a few days.
