### ISSUE TITLE
Automatic serializer class lookup for Rails?

### ISSUE THREAD

**Issue by frsyuki** [okuramasafumi/alba#210]
## Is your feature request related to a problem? Please describe.

We have following code in a controller of our Rails application:

```ruby
def index
  nodes = Node.where(index_conditions).map {|node| node.real_node }
  render json: nodes, action: 'index'
end
```

`Node#real_node` method is a polymorphic association like this:

```ruby
class Node < ApplicationController
  belongs_to :real_node, polymorphic: true
end
```

Because elements of the rendered array dynamically change at runtime, I can't determine serializer class statically.

## Describe the solution you'd like

To overcome the problem, I added following initializer file at `config/initializers/` in our rails app:

```ruby
module AlbaSerializerLookup
  CLASS_SERIALIZER_CACHE = {}

  def self.serializer_for(object, serializer: nil)
    if serializer
      if serializer.is_a?(String) || serializer.is_a?(Symbol)
        serializer = ActiveSupport::Inflector.safe_constantize(serializer)
      end
      serializer
    else
      serializer_for_class(object.class)
    end
  end

  def self.serializer_for_class(klass)
    CLASS_SERIALIZER_CACHE[klass] ||= serializer_for_class_without_cache(klass)
  end

  def self.serializer_for_class_without_cache(klass)
    # This returns ArraySerializer if klass is Array
    ActiveSupport::Inflector.safe_constantize(:"#{klass.name}Serializer")
  end
end

class ObjectSerializer
  include Alba::Resource

  def converter
    inner_params = params.dup
    inner_serializer_param = inner_params.delete(:serializer)

    lambda do |object|
      serializer = AlbaSerializerLookup.serializer_for(object, serializer: inner_serializer_param)
      if serializer && serializer != ObjectSerializer
        resource = serializer.new(object, params: inner_params)
        resource.serializable_hash
      else
        object
      end
    end
  end
end

class RootSerializer < ObjectSerializer
  def serializable_hash
    if collection? && !object.is_a?(Hash)
      root_array_serializable_hash
    else
      converter.call(object)
    end
  end

  alias to_h serializable_hash

  private

  def root_array_serializable_hash
    serializable_array = object.map(&converter)

    if object.respond_to?(:total)
      {
        data: serializable_array,
        total: object.total,
      }
    else
      {
        data: serializable_array,
      }
    end
  end
end

ActionController::Renderers.add :json do |object, options|
  resource = RootSerializer.new(object, params: options)
  string = resource.serialize
  send_data string, type: Mime[:json]
end
```

This approach is basically inspired by following logics of ActiveModelSerializers:

* [ActiveModelSerializers::LookupChain](https://github.com/rails-api/active_model_serializers/blob/0fbe0fad0dec9368e9335b6280a46ca13442727e/lib/active_model_serializers/lookup_chain.rb) to lookup a serializer class from `object.class` dynamically
* [railtie code](https://github.com/rails-api/active_model_serializers/blob/0-10-stable/lib/active_model_serializers/railtie.rb#L16-L20) that adds support for `render json: ...` syntax

Support for `render json: ...` syntax is useful when we want to support both HTML and JSON response from the same controller method, although we're not using it at this moment:

```ruby
def index
  nodes = Node.where(index_conditions).map {|node| node.real_node }
  respond_to do |format|
    format.json {render json: nodes}
    format.html  {render json: nodes}
  end
end
```

## Describe alternatives you've considered

It would be great if Alba gem has out-of-the-box support for json rendering for Rails with dynamic serializer class lookup.

## Additional context

Verified code snippets with:

* rails-7.0.3
* alba-1.6.0

**Comment by frsyuki** [comment]
@okuramasafumi Thank you for updates!

ActiveModelSerializers overrides `render json: ...` but It's totally OK to use a new symbol such as `render alba_json: ...`.

> For serializer lookup, Alba already implement simple approach

I wasn't aware of it but it looks great. Here I have another uncovered use case:

```
class FolderNode < ApplicationController
  has_many :child_nodes, polymorphic: true
end

class FolderResource
  include Alba::Resource

  many child_nodes, resource: HERE
end
```

At `HERE` in above code, what is a suggested resource/serializer class we should use?

**Comment by okuramasafumi** [comment]
OK, I'll add a configuration that allows to override default `render json:`.

For the case you mention, you can skip `resource` option and Alba will infer resource for that association as well.

If you have complex logic for polymorphic association in your app, I think using a `Proc` for `resource` option might be neat. It's currently NOT possible since not implemented yet.
The code will look like this:

```ruby
class FolderNode < ActiveRecord::Base
  has_many :child_nodes, polymorphic: true
end

class FolderResource
  include Alba::Resource

  many child_nodes, resource: ->(node) { node.folder? ? FolderResource : FileResource }
end
```

**Comment by frsyuki** [comment]
> I think using a Proc for resource option might be neat.
That sounds like a good idea!

**Comment by frsyuki** [comment]
> different resources for each object. This causes performance issue

Considering polymorphic association, I think it's unavoidable performance impact.
We have only a few polymorphic `many` associations and thus it's acceptable.

**Comment by frsyuki** [comment]
Great! Thank you!!
