### ISSUE TITLE
Compatibility with zeitwerk

### ISSUE THREAD

**Issue by ima2251** [okuramasafumi/alba#212]
## Describe the bug
When I write certain code, I get an error in zeitwerk:check.

```
$ rails zeitwerk:check                                                        
Hold on, I am eager loading the application.
rails aborted!
NameError: uninitialized constant CommentResource::CommentParentResource

  one :parent, resource: CommentParentResource
                         ^^^^^^^^^^^^^^^^^^^^^
/alba-zeitwerk-issue/app/resources/comment_resource.rb:7:in `<class:CommentResource>'
/alba-zeitwerk-issue/app/resources/comment_resource.rb:1:in `<main>'
/alba-zeitwerk-issue/app/resources/comment_parent_resource.rb:1:in `<main>'
Tasks: TOP => zeitwerk:check
```

## To Reproduce

reproduction code
https://github.com/ima2251/alba-zeitwerk-issue

## Expected behavior
No error in zeitwerk:check.

## Environment
- Please check my repository.

## Additional context

Random error when deploying to Heroku.Sometimes it deploys successfully, sometimes it fails.
The cause of the error is the same as with zeritwerk:check.

Normal code works fine, so we won't notice it during normal development, unless we do a zeitwerk:check.

**Comment by okuramasafumi** [comment]
@ima2251 
In your case, `CommentParentResource` inherits from `CommentResource`, and `CommentResource` refers to `CommentParentResource`. This causes circular dependencies.
This problem might be resolved by making reference a String. So it looks like:

```ruby
one :parent, resource: 'CommentParentResource'
```

I confirmed that `zeitwerk:check` passes with this. Could you confirm that this works for you?

**Comment by ima2251** [comment]
@okuramasafumi 
It works fine!
Thank you.
