### ISSUE TITLE
Change/Override params in associations

### ISSUE THREAD

**Issue by lukaspili** [okuramasafumi/alba#216]
Would it be possible to allow something like this?

```ruby
class FooJson
  include Alba::Resource
  one :bar, resource: BarJson, params: { some: "other_value" }
end

FooJson.new(data, params: { some: "value" }).serialize
```

Thanks!

**Comment by okuramasafumi** [comment]
@lukaspili Hi, it's currently not possible but if there're some usecases I'd like to support it.
Could you share your usecase? For example, what kind of JSON output you want with given object?

**Comment by lukaspili** [comment]
Thanks for the quick reply!
My concrete use case is that I want to expose different attributes depending on permissions.
This is simple example with one nesting, but I have some use cases where the `scope` params is passed down to several nested associations.

```ruby 
class UserJson
  include Alba::Resource

  attributes :email_address, if: proc { params[:scope] == "session" }
end

class ContractJson
  include Alba::Resource

  one :creator, resource: UserJson # apply session scope 
  one :counter_party, resource: UserJson # apply anon scope 
end
```

**Comment by okuramasafumi** [comment]
One way to achieve this goal would be to use inheritance, for example:

```ruby
class UserJson
  include Alba::Resource

  attributes :email_address
end

class AnonUserJson < UserJson
  def attributes
    super.reject {|k, v| k == :email_address}
  end
end
```

`AnonUserJson` is a customized version of `UserJson` that rejects some attributes.

**Comment by okuramasafumi** [comment]
True. Would you implement this feature on your own? If you will I can help.
If not, then don't worry, I'll implement it.

**Comment by lukaspili** [comment]
Sorry - I won't have time to tackle it. Thanks in advance if you do it, but if not I understand!

**Comment by okuramasafumi** [comment]
Hi @lukaspili , at #227 I've implemented this feature. I added some descriptions to README so please could you check it and see if it's good for you?

**Comment by lukaspili** [comment]
Hi @okuramasafumi sorry for the late reply. It looks good :) Thank you!
