### ISSUE TITLE
Can't get root_key to work (without inference)

### ISSUE THREAD

**Issue by jrochkind** [okuramasafumi/alba#234]
## Describe the bug
:root_key does not seem to be doing what I expect, I can't get it to have an effect. I am _not_ using inference, but still expect to be able to specify a root key manually. 

## To Reproduce
```ruby
class MyThing
  attr_accessor :name
  def initialize(name:)
    @name = name
  end
end

class TestSerializer
  include Alba::Resource

  root_key :widget

  attributes :name
end

TestSerializer.new( MyThing.new(name: "joe") ).serializable_hash
# => {:name=>"joe"}
```

## Expected behavior
I expected there to be a root key in the output, like

```ruby
{ widget: {:name=>"joe"} }
```

## Actual behavior
There is no root key  in the output, just `{:name=>"joe"}`. The `root_key` seems to be ignored?

This also means I can't get `meta` to output, because it requires a recognized `root_key`. 

## Additional context
Alba 1.6.0

I know the `root_key` function is integrated with "inference", I am _not_ using alba inference, _not_ calling `Alba.enable_inference!`, not sure if that matters.

**Comment by okuramasafumi** [comment]
@jrochkind Sorry for the confusion, but `serializable_hash` doesn't get any effect of `root_key`. You can still get a hash with root key by `JSON.parse(TestSerializer.new( MyThing.new(name: "joe") ).serialize`.

I know it's confusing, so at least I'll add some note to README. Probably I'd like to add options to make `serializable_hash` work like `serialize`.

So please keep this issue open until I ship some fixes!

**Comment by jrochkind** [comment]
Oh, I see. That was unexpected!

It would be very convenient to be able to get exactly the same data structure as a ruby hash pre-serialization as I would get serialized, whether that's with the `serializable_hash` method or a different method -- in general I expected `serializable_hash` and `serialize` would produce equivalent output, just one a ruby hash and one serialized to json), and I'm not sure why they shouldn't! 

Obviously re-parsing the serialized string is not a great solution. 

Thanks!

**Comment by okuramasafumi** [comment]
It's confusing because `serializable_hash` has two purposes: internal usage for generating final JSON output and exposed interface for getting hash representation.
We should probably split them into two separate methods, one for internal and one for external.

**Comment by okuramasafumi** [comment]
@jrochkind Hi, I'm addressing this issue by #241 
Could you check out README of the PR and see if the behavior is what you want?

**Comment by okuramasafumi** [comment]
@jrochkind Thank you for your suggestion. We can maybe add an option `as: :hash` to `serialize` method.

**Comment by okuramasafumi** [comment]
I also came up with `serialized_hash`, but the name is little confusing.

**Comment by okuramasafumi** [comment]
@trevorturk Without considering backward compatibility, it's relatively easy to change the behavior of `to_h` and `serializable_hash`. We can change the behavior of `to_h` only so that `to_h` works like `serialize`, and keep the behavior of `serializable_hash` as is.
The difficulty here is to let people that use `to_h` and `serializable_hash` interchangeably to use them correctly. Although the next version is `2.0` and we change add breaking changes, I don't want the migration path to be too complex.

**Comment by jrochkind** [comment]
Changing the behavior of one of #to_h or #serializable_hash to match #serialize doesn't outwardly seem to me to create a difficult migration path, you can just change what method you call if the other is still available? 

Although it may be harder if there is intermediate software calling one of those methods as a standard interface... do we know if that's going on?  #serializable_hash seems maybe more likely that someone is relying on it doing a certain thing -- although I still would have assumed the opposite thing of what it does now, that `serializable_hash` directly corresponds to what gets actually serialized, from the name and I think other rails behavior.  So I'm not sure. 

Does anyone know of use cases that might make it a difficult migration path if one (but not both?) of these methods changed? For instance, cases where you can't easily just change what method is being called because maybe it's somebody else's code calling the method, as a standard interface.

**Comment by trevorturk** [comment]
Ah, yeah, that might be a nice approach. FWIW I had a PR with Rails recently where I added a breaking change and plugged into their `load_defaults` system: https://github.com/trevorturk/rails/blob/0ae0ab7e3ff040e1b04c600944ba4f643954760a/railties/lib/rails/application/configuration.rb#L85-L89

This is probably much too complex for Alba, but it might be worth considering having a set of defaults per major version kind of like this, even if in a simplified form. (Of course, also great to have specific flags that people could set. In this case I might describe the intention, which might be `Alba.include_root_key_in_serializable_hash` or something like that. This could be `true` by default, and the release notes could specify to set it to `false` in an initializer if upgrading and desired. 

Anyway, apologies for bike-shedding and poking my nose in here! I really have been enjoying Alba, and I want to thank you again!

**Comment by okuramasafumi** [comment]
@trevorturk Now I change https://github.com/okuramasafumi/alba/pull/241 to include root key by default. We can turn if off by wither adding `root_key: false` or defining `default_root_key` method to return `false`. I didn't add global flag for this since I'd like to reduce the number of global flags and go toward more OOP style like this.

**Comment by trevorturk** [comment]
Thank you for this! I'd like to have a closer look to provide feedback, because I was a bit confused with the README changes, and I want to have a better understanding.

**Comment by okuramasafumi** [comment]
@trevorturk I'm sorry, please submit a PR to improve README if you could!

**Comment by trevorturk** [comment]
Ok, I was able to spend some time with this, and I worked up a PR #247 which I hope may help clarify the documentation, and also describes where I became confused and suggests considering an additional change. Please take all of this with a grain of salt, as I'm not sure I'm entirely correct in my thinking, but I hope the PR may be helpful in any case!

**Comment by okuramasafumi** [comment]
I also think now that `as_json` is available for Alba.
https://api.rubyonrails.org/classes/ActiveModel/Serializers/JSON.html#method-i-as_json
`to_json` and `as_json` should behave similarly, so we can keep `serializable_hash` and `to_h` implementation as is and implement new behavior in `as_json`.

**Comment by jrochkind** [comment]
#as_json will return a Hash with the same contents as #serialize? That seems like a great  solution to me, awesome, thank you!

**Comment by trevorturk** [comment]
One caveat is that you may still consider if to_h and to_json being different may be confusing, but that would be a breaking change.
