### ISSUE TITLE
Dynamic filter

### ISSUE THREAD

**Issue by ManuelCostanzo** [okuramasafumi/alba#243]
Hi! Thanks for the project.

I would like to ask if there is a way to include/exclude attributes via params, for example something like this:

`UserResource.new(user, exclude: {[:id]})`,

should return the json without the "ID".

Thank you!

**Comment by okuramasafumi** [comment]
@ManuelCostanzo It's not possible to exclude ad hoc attributes. However, you can do so by normal `params`.

```ruby
class UserResource
  include Alba::Resource

  root_key :user

  attributes :id, if: proc { !params[:exclude]&.include?(:id) }
  attributes :name, :email
end

User = Struct.new(:id, :name, :email)
user = User.new(1, 'John Doe', 'test@example.org')

UserResource.new(user, params: {exclude: [:id]}).serialize # => '{"user":{"name":"John Doe","email":"test@example.org"}}'
```

The reason why Alba doesn't support ad hoc exclude is that we want to make it easy to predict output by just looking at the resource class. In this example, although we need to add explicit `if` option for exclude logic, it's easy to know in some places `id` will be actually excluded. In contrast, if we provide `exclude` option, while we don't have to add `if` option, it's more difficult to know in some cases we exclude `id`.

**Comment by ManuelCostanzo** [comment]
Thank you very much. That make sense!
