### ISSUE TITLE
Question about render :json

### ISSUE THREAD

**Issue by ManuelCostanzo** [okuramasafumi/alba#244]
Hi! I have another question related with render :json in rails controller.

Is there a way to automatically serialize with alba using render? If not, what is the recommended way to use alba in a rails controller.

Thank you!

**Comment by okuramasafumi** [comment]
Ah sorry now I got what you want. Yes it works with AMS, but to make it work it hacks ActionController like this:
https://github.com/rails-api/active_model_serializers/blob/0-10-stable/lib/action_controller/serialization.rb

I'm not sure if it deserves this 70 lines of code. After all, we can call `UserSerializer#new` as you do and everything works.
