### ISSUE TITLE
Stack level too deep

### ISSUE THREAD

**Issue by firstpromoter** [okuramasafumi/alba#261]
## Describe the bug
Getting "Stack level too deep" if I add nested relationship.
## To Reproduce
```
class AccountSerializer
      include Alba::Resource
      attributes :id, :role
      one :user, resource: UserSerializer
  end
```

```
class UserSerializer
      include Alba::Resource
      attributes :id, :email,:created_at
      many :accounts, resource: AccountSerializer
end
```

controller:
`render json: AccountSerializer.new(accounts)`

## Expected behavior
To just render one level deep relationship and exit. Ideally we should be able how deep it can go like AMS allows.

## Actual behavior
I guess it tries to re-render everything one inside another.

## Environment
- Ruby version: 2.7.6

## Additional context
Rails 7

**Comment by okuramasafumi** [comment]
@firstpromoter https://github.com/okuramasafumi/alba#circular-associations-control does this help?

**Comment by firstpromoter** [comment]
I haven't tried it, but that error shouldn't happen in the first place in my opinion. The "within" option forces us to pass nesting logic to each controller action which is not great. I think by default it should just render once and stop.

**Comment by okuramasafumi** [comment]
I know what you mean, but if Alba stops at 1 level by default, it needs to remember nesting level, which I don't want to do.
I can suggest another solution that uses `if` option and abuses filtering feature.

```ruby
class AccountSerializer
  include Alba::Resource
  attributes :id, :role
  one :user,
      proc { |user, params|
        nesting_level = params[:nesting_level] || 0
        params[:nesting_level] = nesting_level + 1
        user
      },
      resource: 'UserSerializer'
end

class UserSerializer
  include Alba::Resource
  attributes :id, :email, :created_at
  many :accounts, resource: 'AccountSerializer', if: proc { (params[:nesting_level] || 0) < 1 }
end
```

In this code, `AccountSerializer` has a "side effect" when adds `user` association. It increments `nesting_level` params and we can check it in `UserSerializer` to control nesting level.
It's important that this solution is done at the class level.
I know it's not really ideal, but it works. As I mentioned, I don't want to track nesting level in Alba itself, but rather I'd like to let users do it easily.
I'll implement a new feature when I come up with good solution.

**Comment by firstpromoter** [comment]
Thanks. That's a solution but not ideal. If we're about to use "within" in controller, how would this work? Or is there any easier solution than counting nesting level?

**Comment by okuramasafumi** [comment]
```ruby
AccountSerializer.new(account, within: :user)
```

This should work, however, in version 2, it includes `accounts: null` instead of not having `accounts` key.
This seems a bug so I'll fix it soon.

**Comment by okuramasafumi** [comment]
@firstpromoter Does `within` work for you? If so' I'll close this issue. If not, I'll try to find other solutions.

**Comment by okuramasafumi** [comment]
I'm closing this due to no response. Feel free to reopen if it still occurs.
