### ISSUE TITLE
When Alba.inferring is false, either resource or block is required

### ISSUE THREAD

**Issue by danielmalaton** [okuramasafumi/alba#275]
## Describe the bug
Include module which `extend ActiveSupport::Concern` and it use `included` will raise **Alba.inferring is false, either resource or block is required**

## To Reproduce
In my serializer:
```Ruby
class ABCSerializer
  include Alba::Resource
  ...
  include XYZSerializerHelper
  ...
end
```
In XYZSerializerHelper module:
```Ruby
module XYZSerializerHelper
  extend ActiveSupport::Concern
  included do
    one :auto_preload
  end

  def auto_preload
    # do something
  end
end
```

## Expected behavior
It works normally

## Actual behavior
When Alba.inferring is false, either resource or block is required

## Environment
- Ruby version: 2.7.4

## Additional context
Rails 6.0.x

**Comment by danielmalaton** [comment]
Update: Follow this guide to add configuration to backend.

**Comment by okuramasafumi** [comment]
@danielmalaton Did you add `Alba.enable_inference!(with: :active_support)` in your Rails initializer?

**Comment by danielmalaton** [comment]
Okay tysm. It works.

**Comment by danielmalaton** [comment]
But atm, it raise Wrong constant name at `one :auto_preload` in
```Ruby
  included do
    one :auto_preload
  end
```
Do you have any idea for it? @okuramasafumi

**Comment by okuramasafumi** [comment]
What do you mean by "wrong"? Could you provide a concrete example?

**Comment by okuramasafumi** [comment]
Ah I see. It's not `one` that you should use here. You can use `attributes` here instead of `one`.
You can check the document [here](https://github.com/okuramasafumi/alba#simple-serialization-with-root-key).

**Comment by danielmalaton** [comment]
Okay. It works normally know.
