### ISSUE TITLE
Support proc in one associations

### ISSUE THREAD

**Issue by alejandroperea** [okuramasafumi/alba#279]
Maybe I'm doing something wrong, I'll try to explain the case. Imagine that we have:

```
class Soundtrack < ApplicationRecord
  ...
  belongs_to :content, polymorphic: true
  ...
end
```

Then, in the serializer I would like to have:

```
class SoundtrackResource < ApplicationResource
  ...
  one :content, resource: ->(content) { content.is_a?(Movie) ? BasicMovieResource : BasicTvShowResource }
  ...
end
```

But this is not working. Deeping a little bit into the code, I've found this method:

```
    def to_h(target, within: nil, params: {})
      params = params.merge(@params) unless @params.empty?
      @object = target.__send__(@name)
      @object = @condition.call(object, params, target) if @condition
      return if @object.nil?

      if @resource.is_a?(Proc) && @object.is_a?(Enumerable)
        to_h_with_each_resource(within, params)
      else
        to_h_with_constantize_resource(within, params)
      end
    end
```

So, if the resource is a Proc (this is the case) it is also expecting that the object is Enumerable, not calling the proc because is going to the `else` execution branch, because this association is only one element.

Am I doing something wrong?

Thanks!

**Comment by okuramasafumi** [comment]
@alejandroperea Thank you for the report. You're not wrong, this is my mistake and I'll fix this bug soon.

**Comment by alejandroperea** [comment]
Thanks @okuramasafumi !

I've opened a couple of PRs, for helping a little bit:

https://github.com/okuramasafumi/alba/pull/280
https://github.com/okuramasafumi/alba/pull/281

**Comment by alejandroperea** [comment]
Addressed here: https://github.com/okuramasafumi/alba/pull/281

Closing the issue.

**Comment by alejandroperea** [comment]
Addressed here: https://github.com/okuramasafumi/alba/pull/281

Closing the issue.

**Comment by kapso** [comment]
@okuramasafumi we have to use the following standard code for all polymorphic relationship, why not add support for `polymorphic: true`  

```ruby
one :visitable, resource: ->(relation) { "App::V2::#{relation.class.name}Serializer".constantize }
```

**Comment by okuramasafumi** [comment]
@kapso I'm not sure what should happen when `polymorphic: true` is given. You could suggest me how it should behave or submit a patch for this feature.

**Comment by kapso** [comment]
@okuramasafumi when `polymorphic: true`, it should infer the serializer based on relation class name
