### ISSUE TITLE
Can you release a new gem version to use `select`?

### ISSUE THREAD

**Issue by vizcay** [okuramasafumi/alba#283]
Hey, thanks for your work here.

I was trying to filter attributes with nil values, when I've found about `select` in the docs. But seems not included in `2.0.1` and looks like cannot be done with `attributes`.

Any chance to release `2.1.0` soon then? So we don't have to be pulling from `main` in the `Gemfile`.

Best

**Comment by okuramasafumi** [comment]
Hi @vizcay I just published `2.1.0` so please check it out!
https://rubygems.org/gems/alba/versions/2.1.0

**Comment by vizcay** [comment]
Thanks @okuramasafumi.
