### ISSUE TITLE
Support Sorbet?

### ISSUE THREAD

**Issue by danielmalaton** [okuramasafumi/alba#285]
## Is your feature request related to a problem? Please describe.
Do you have a plan for supporting Sorbet in the future? If not, why?

## Describe the solution you'd like
Support Sorbet is a fancy approach to make Alba more type-safe.

**Comment by okuramasafumi** [comment]
@danielmalaton Mainly because I don't use Sorbet. That said, I need support from those who have used Sorbet before. Actually I don't get what "supporting Sorbet" means.

**Comment by danielmalaton** [comment]
I mean if any application has already used Sorbet and wants to use Alba as a serializer gem, it will adopt smoothly.

**Comment by okuramasafumi** [comment]
I'm happy if you provide sample application that uses Sorbet and Alba :)

**Comment by okuramasafumi** [comment]
@danielmalaton I'm not familiar with Sorbet and I need some help, otherwise I'll leave this issue undone.
