### ISSUE TITLE
How do we deal with a `nil` object

### ISSUE THREAD

**Issue by danielmalaton** [okuramasafumi/alba#305]
## Is your feature request related to a problem? Please describe.
Suppose I have an Alba serializer like `DataSetResource`.
I want to serialize a dataset, but it can be nilable. I know serializing a nil object will throw an error in Alba.
```Ruby
  DataSetResource.new(dataset).as_json
```

## Describe the solution you'd like
Would you provide a new optional params `nilable` like:
```Ruby
  DataSetResource.new(dataset, nilalbe: true).as_json
```

## Additional context
I know I can check nil before serializing. But it sounds inconvenient as many legacy codes have serialized with `nil` object (with the help of Active Model Serializer).

**Comment by okuramasafumi** [comment]
@danielmalaton 

When you call

```ruby
DataSetResource.new(dataset, nilable: true).as_json
```

what would you expect? If you expect `nil` then

```ruby
DataSetResource.new(dataset).as_json unless dataset.nil?
```

would be equivalent.

If you expect something other than `nil`, then we need some DSL to define that value. For example,

```ruby
class DataSetResource
  handle_nil { {} }
end
```

However, this is essentially the same as:

```ruby
dataset.nil ? {} : DataSetResource.new(dataset).as_json
```

so I'm not sure if it's worth adding a new DSL.

**Comment by okuramasafumi** [comment]
@danielmalaton I'm closing it now, but feel free to reopen if you still have an issue.

**Comment by danielmalaton** [comment]
Thanks for supporting!

**Comment by remy727** [comment]
Can you support `handle_nil`?

```ruby
class SettingResource
  include Alba::Resource

  root_key :setting, :settings

  attributes :id,
    :activated
end

class AuthenticatedController < ApplicationController
  before_action :set_shop

  def set_shop
    @shop ||= Shop.find_by(shopify_domain: current_shopify_domain)
  end
end

class Api::SettingsController < AuthenticatedController
  def index
    render json: SettingResource.new(@shop.setting).serialize
  end
end
```

If `@shop` has setting, `render json: SettingResource.new(@shop.setting).serialize` will render
```json
{
  "setting": {
    "id": 1,
    "activated": true,
  }
}
```
I can handle `nil` in the controller like the following but this looks not good.
```ruby
setting = if @shop.setting.present?
    SettingResource.new(nil).serialize
  else
    { setting: {} }
  end
render json: setting
```

**Comment by okuramasafumi** [comment]
@remy727 What would you expect from `handle_nil`?

**Comment by remy727** [comment]
```ruby
class SettingResource
  include Alba::Resource

  handle_nil { {} }

  # rest
end
```

What I expect:
```bash
[1] pry(main)> SettingResource.new(@shop.setting).serialize
=> { setting: {} }
```

**Comment by okuramasafumi** [comment]
I got it. IMO dealing with "errors" is the responsibility of a controller. In this case I'd prefer slightly modified version of your code:

```ruby
if @shop.setting.present?
  render json: SettingResource.new(@shop.setting).serialize
else
  render json: { setting: {} }
end
```

This code is clear about what is returned when setting exists or not. It's easier to read and debug.

The problem of `handle_nil` is that it dramatically changes the schema it returns. It can be difficult to debug such code.

**Comment by remy727** [comment]
I got it. I agree with you. Thank you for your support 🙏

**Comment by bhrama-br** [comment]
Hi, could you help me? I'm trying to return nil when the object is nil.
But it always returns {}. Is it possible to control this return through serialize?

**Comment by okuramasafumi** [comment]
@bhrama-br I recommend checking nil outside of the serializer as described above. Is there any problem doing so?

**Comment by bhrama-br** [comment]
yes, As I am migrating code to Alba, before it returned nil.

What I did was:

`    def serializable_hash
      if collection?
        serializable_hash_for_collection
      else
        @object.blank? ? nil : converter.call(@object)
      end
    end`
    
    
    It worked well for me. thanks

**Comment by okuramasafumi** [comment]
@bhrama-br Yes it should work, but is not a recommended way. At least we don't want to know the implementation of `serializable_hash` method.

```ruby
def serializable_hash
  return if @object.blank?

  super
end
```

I'd prefer using `super`.
