### ISSUE TITLE
Configure how date objects are serialized

### ISSUE THREAD

**Issue by rwehresmann** [okuramasafumi/alba#308]
Is there a way to configure how dates should be serialized? For instance: `TimeWithZone` is displayed as "2000-01-01 08:00:00 UTC", when the standard I want is "2000-01-01T08:00:00.000Z". I can handle this manually for each date attribute using types for conversion, but it would be nice to have a config to avoid remembering to do this every time.

**Comment by okuramasafumi** [comment]
Typically you can change Date serialization format by setting backend, e.g. `Alba.backend = :active_support`

If this is not preferable currently there's no way to configure Date format only.
It might be good to add global type conversion support, but we need to consider its usage and API before implementing.

**Comment by okuramasafumi** [comment]
@rwehresmann Are you satisfied with the solution above? If so I'll close this issue.

**Comment by rwehresmann** [comment]
@okuramasafumi  It didn't solve the issue, I'm handling formatting it manually resource by resource. The global conversion is still a good ideia, in my opinion.

**Comment by okuramasafumi** [comment]
@rwehresmann I see. Implementing global conversion is something I would try, but it takes some time to consider the spec so that it doesn't affect performance and maximizes usability.
I keep this open until we implement it so that we can track it as not-implemented.

**Comment by okuramasafumi** [comment]
Do you use Rails? If so, as described in https://api.rubyonrails.org/classes/ActiveSupport/TimeWithZone.html#method-i-as_json you can change global `TimeWithZone` conversion by setting `ActiveSupport::JSON::Encoding.use_standard_json_time_format` to `false`.

**Comment by rwehresmann** [comment]
Yeap, I'm using rails, but disabling the standard json time format still doesn't give the format I need. In my particular case I need the `iso8601(3)`.

**Comment by okuramasafumi** [comment]
@rwehresmann Sorry for the late response, I came up with the following:

```ruby
attribute :some_time do |object|
  object.some_time.iso8601(3)
end
```

**Comment by rwehresmann** [comment]
@okuramasafumi tks, I'm using `some_time: [String, ->(object) { object.iso8601(3) }]`, but that works too!

**Comment by okuramasafumi** [comment]
@rwehresmann Are you satisfied that solution? If so, I'll close this issue.

**Comment by rwehresmann** [comment]
@okuramasafumi I'd like to have a general configuration to make `iso8601(3)` the default date format, so I don't need to remember to transform the date in each resource. But if it's in the plans to have something like that, I can live without it, so feel free to close this issue.

**Comment by okuramasafumi** [comment]
@rwehresmann Thank you, I don't think using `iso8601(3)` is general enough not I'm not planning to support it directly with Alba.
However, I'm considering adding support for custom types so that you can do something like:

```ruby
Alba.register_type :ISO8601, check: ->(object) { object.is_a?(String) }, converter: ->(object) { object.iso8601(3) }

some_time: :IOS8601
# Same as
# some_time: [String, ->(object) { object.iso8601(3) }]
```

This would be much more DRY than the current solution.

**Comment by rwehresmann** [comment]
@okuramasafumi this would be great!

**Comment by okuramasafumi** [comment]
@rwehresmann Hi, now Alba's `main` branch has custom type feature! You can try it by cloning it, running `bin/setup` and `bin/console`. If that seems good I'll close this issue.

**Comment by rwehresmann** [comment]
It seems good! Thanks @okuramasafumi !

**Comment by leewaa** [comment]
Is there a way to define how **all** datetime/date fields are serialized per default, without having to define it everywhere a datetime/date should be serialized?

IMHO an API should define how dates are returned / accepted overall and not individually, thus keeping to a consistent format.

**Comment by okuramasafumi** [comment]
@leewaa In fact, serializing Time/DateTime is done by `json` or `oj` library. Alba doesn't do any specific thing about it.

I believe you can redefine `Time#to_json` and `DateTime#to_json` to achieve what you want, at least if you use `json` backend:

```ruby
class Time
  def to_json(*)
    # Whatever you want
  end
end
```

**Comment by leewaa** [comment]
> @leewaa In fact, serializing Time/DateTime is done by json or oj library. Alba doesn't do any specific thing about it.

Yes of-course, that's what I mean: I think it would be great if alba had this feature. I dislike monkey patching and don't want to tightly couple my needs with rails core functionality.
