### ISSUE TITLE
[Oj] Options from Oj are ignored

### ISSUE THREAD

**Issue by danielmalaton** [okuramasafumi/alba#310]
**Context**
I'm using [`oj`](https://github.com/ohler55/oj) in Alba Resource
The config is like:
```Ruby
# in config/initializers/alba.rb
Alba.enable_inference!(with: :active_support)
Alba.backend = :oj
```
When I render, a warning message is thrown 
<img width="956" alt="image" src="https://user-images.githubusercontent.com/106505755/227771179-82b46f3b-f41c-4132-a4c9-69522d3cf4c1.png">

In your document, I read that you [ignore almost options](https://github.com/okuramasafumi/alba/blob/main/docs/rails.md#rendering-json). 

**Problem**
I'm doubtful does the `oj` is using. Or is there any way to use/config `oj` properly? Correct me if I'm wrong. Many thanks for considering my request.

**Comment by okuramasafumi** [comment]
@danielmalaton I believe you're using Oj properly because there's no signal that it's not working.
If you can share the code that actually calls `render` with options, I might be able to give some advice.

**Comment by okuramasafumi** [comment]
@danielmalaton OK, your code will do something like this:

```ruby
serialized_string = DataSetResource.new(obj).as_json(root_key: root_key)
render {}.merge(json: MultiJson.dump(serialized_string))
```

So you basically serialize object twice, once with Alba and again with MultiJson. Is it intended?

**Comment by danielmalaton** [comment]
Thanks for the advice. But it does not seem not to work. The piece of code in `initializer/alba.rb` looks like:
```Ruby
Alba.enable_inference!(with: :active_support)
# Alba.backend = :oj

Alba.encoder = proc do |object|
  Oj.dump(object, { mode: :compat, time_format: :ruby, use_to_json: true })
end
```

The warning message shows the same as in the beginning. Even if I change to empty options:
```Ruby
Alba.enable_inference!(with: :active_support)
# Alba.backend = :oj

Alba.encoder = proc do |object|
  Oj.dump(object)
end
```
The warning message still shows

**Comment by okuramasafumi** [comment]
That's weird. That warnings are displayed only when options are passed to `to_json`, which Rails automatically does with something like `render json: FooResource.new(foo), this: :option` When `to_json` is explicitly called there should be no warnings.

**Comment by danielmalaton** [comment]
Thanks for your points. After investigating, I have found that the gem `MultiJson` automatically adds extraneous options to the `render` function. This is the root cause. 

I will close this issue. Thanks!
