### ISSUE TITLE
Can't call class method within `has_many`

### ISSUE THREAD

**Issue by george-ayris** [okuramasafumi/alba#321]
## Describe the bug
I'd like to DRY out some serializer code by introducing a shared (base) class method, but that method can only be called from the top level of the resource and not from within a `has_many`.

This might not actually be a bug, but it's not how I'd expect it to work.

## To Reproduce
Run the following:
```rb
class Library
  def id
    1
  end

  def library_books
    [Book.new(), Book.new()]
  end

  def created_at
    Time.now
  end
end

class Book
  def id
    1
  end

  def created_at
    Time.now
  end
end

class ApplicationResource
  include Alba::Resource

  def self.has_id
    attributes :id
  end
end

class LibraryResource < ApplicationResource
  has_id
  attributes :created_at

  has_many :library_books do
    has_id
    attributes :created_at
  end
end

LibraryResource.new(Library.new()).to_h
```

## Expected behavior
Serialize to:
```rb
{"id"=>1, "createdAt"=>2023-07-12 16:39:26.753095 +0100, "libraryBooks"=>[{"createdAt"=>2023-07-12 16:39:26.753406 +0100}, {"id"=>1, "createdAt"=>2023-07-12 16:39:26.753432 +0100}]}
```

## Actual behavior
Get the following error:
```
40:in `block in <class:LibraryResource>': undefined local variable or method `has_id' for #<Class:0x000000010a3273e0> (NameError)
```

## Environment
- Ruby version: ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21]

## Additional context
For reference the following works, but is missing the `id` in the `library_books`:
```rb
class LibraryResource < ApplicationResource
  has_id
  attributes :created_at

  has_many :library_books do
    attributes :created_at
  end
end
```

My workaround for the moment is:
```rb
class ApplicationResource
  include Alba::Resource

  module Helpers
    def has_id
      attributes :id
    end
  end
  extend Helpers
end

class LibraryResource < ApplicationResource
  has_id
  attributes :created_at

  has_many :library_books do
    extend ApplicationResource::Helpers

    has_id
    attributes :created_at
  end
end
```

**Comment by okuramasafumi** [comment]
@george-ayris Simple inheritance turned out not a good solution. I'd suggest the style below.

```ruby
class ApplicationResource
  include Alba::Resource

  helper do
    def has_id
      attributes :id
    end
  end
end

class LibraryResource < ApplicationResource
  has_id
  attributes :created_at

  has_many :library_books do
    has_id
    attributes :created_at
  end
end
```

The point is `helper` block, which registers given methods to an anonymous module and extends it for classes and associations. This is similar to your workaround but is less verbose.
What do you think about this solution, is it good enough?

**Comment by george-ayris** [comment]
@okuramasafumi that looks good to me. Thanks for looking at this (and also for all your other work on this project)!

**Comment by okuramasafumi** [comment]
#322 implements helper, and you can see how it works by the test file added in this PR. Does it look good?

**Comment by george-ayris** [comment]
@okuramasafumi looks good to me!
