### ISSUE TITLE
FrozenError: can't modify frozen String

### ISSUE THREAD

**Issue by k1r8r0wn** [okuramasafumi/alba#327]
Hello, found the minor issue.

## Describe the bug
```ruby
FrozenError: can't modify frozen String: "private def _setup;"
```
in https://github.com/okuramasafumi/alba/blob/ab5a6ff21a90512d1272a3ccb35573e1180ac387/lib/alba/resource.rb#L24

## To Reproduce
Enabled rule in the core lib which  has:

```yaml
Style/FrozenStringLiteralComment:
  EnforcedStyle: always_true
```

## Possible fix

**To disable rubocop check directly to the line or method.**

## Expected behavior

The error above is ignored for this string.

## Actual behavior
```ruby
FrozenError: can't modify frozen String: "private def _setup;"
```

## Environment
- Ruby version: 3.2.2

**Comment by okuramasafumi** [comment]
@k1r8r0wn I believe that rule is not enabled. It's easy to fix it just by adding `+` to string, but do we ever need to enable it anyway?

**Comment by k1r8r0wn** [comment]
"Yeah, it's disabled here: https://github.com/okuramasafumi/alba/blob/a37652776e43ab0242822311fa526fc6d8768d0f/.rubocop.yml#L112. I believe it's not a significant refactoring to do. Furthermore, in all projects that use Alba, there won't be a need to disable that Rubocop rule."

**Comment by okuramasafumi** [comment]
I could not find a big advantage to enable it, so I kept it disabled.
I think I'd like to close this issue since it's not actually an "issue".

**Comment by k1r8r0wn** [comment]
Maybe the small reactor with **+** sign will be suitable for this?

**Comment by k1r8r0wn** [comment]
My mistake - it wouldn't help.

I suggest to do it like this (use the double quoted strings in two lines, cause double-quoted literals are not frozen by default): 

```ruby
    # rubocop:disable Metrics/MethodLength, Style/StringLiterals
    def self.included(base)
      super
      setup_method_body = "private def _setup;"
      base.class_eval do
        # Initialize
        DSLS.each do |name, initial|
          instance_variable_set("@#{name}", initial.dup) unless instance_variable_defined?("@#{name}")
          setup_method_body << "@#{name} = self.class.#{name};"
        end
        base.define_method(:encode, Alba.encoder)
      end
      setup_method_body << "end"
      base.class_eval(setup_method_body, __FILE__, __LINE__ + 1)
      base.include InstanceMethods
      base.extend ClassMethods
    end
    # rubocop:enable Metrics/MethodLength, Style/StringLiterals
```

But need to add one more rubocop disable rule to the method.

**Comment by okuramasafumi** [comment]
Actually I tried to enable that rule a few weeks ago, and it worked, but I couldn't find any value. There was no performance benefits, for example.
So for now I don't think I'm going to make String literals frozen.

**Comment by k1r8r0wn** [comment]
I see, no prob, okuramasafumi-san. What do you think about small refactor, that I've left above?

**Comment by okuramasafumi** [comment]
> double-quoted literals are not frozen by default

I could not confirm this. In fact, I confirmed that both single-quoted and double-quoted string are frozen with the magic comment.

**Comment by okuramasafumi** [comment]
@k1r8r0wn You don't have to do that. As I said before, I have a working implementation of frozen string literal. It's just that I don't like that and there's not much benefit.

**Comment by k1r8r0wn** [comment]
No prob, thanks.
