### ISSUE TITLE
Why is resource property required for associations?

### ISSUE THREAD

**Issue by kapso** [okuramasafumi/alba#332]
Why is `resource` property required for associations? Why doesn't it use inference.

Notice the following code errors out with `const_get': wrong constant name  (NameError)`

## To Reproduce
```ruby
class User
  attr_reader :id, :created_at, :updated_at
  attr_accessor :articles

  def initialize(id)
    @id = id
    @created_at = Time.now
    @updated_at = Time.now
    @articles = []
  end
end

class Article
  attr_accessor :user_id, :title, :body

  def initialize(user_id, title, body)
    @user_id = user_id
    @title = title
    @body = body
  end
end

class ArticleSerializer
  include Alba::Resource

  attributes :title
end

class UserSerializer
  include Alba::Resource

  attributes :id

  many :articles
  # many :articles, resource: ArticleSerializer # This works
end
```

## Environment
- Ruby version: 3.2.2
- gem 'rails', '7.0.6'
- gem 'alba', '2.3.0'

**Comment by okuramasafumi** [comment]
I've confirmed this is a bug of Alba. I found a way to fix it so I'll soon publish the next version which contains that fix. Thank you!

**Comment by kapso** [comment]
thank you!

**Comment by okuramasafumi** [comment]
Fixed by https://github.com/okuramasafumi/alba/commit/dab7091efa4a76ce9e538e08efa7349c296a705c

**Comment by kapso** [comment]
@okuramasafumi using the above code, now I am seeing the following error...

```
/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/alba-2.4.0/lib/alba.rb:117:in `infer_resource_class': uninitialized constant ArticleResource (NameError)

      const_parent.const_get("#{inflector.classify(name)}Resource")
                  ^^^^^^^^^^
Did you mean?  ArticleSerializer
```

**Comment by okuramasafumi** [comment]
@kapso Sorry my mistake, current code does not work with the class whose name ends with "Serializer".
Alba supports those classes so this is a bug. I'll release a fix soon.

**Comment by okuramasafumi** [comment]
@kapso Version `2.4.1` was just released and I believe it fixed the bug.

**Comment by kapso** [comment]
@okuramasafumi thanks a lot, it works now
