### ISSUE TITLE
Decimals are being shown as a string

### ISSUE THREAD

**Issue by remy727** [okuramasafumi/alba#338]
## Describe the bug
Hello!

I am a big fan of this gem. But recently, I noticed decimals are not being shown correctly after serialzation.

## To Reproduce
```rb
# app/resources/plan_resource
class PlanResource
  include Alba::Resource

  root_key :plan, :plans

  attributes :id,
    :name,
    ....

  attribute :price do |resource|
    resource.price.round(2)
  end
end

# app/controllers/api/plans_controller.rb
class Api::PlansController < ApplicationController
  def index
    render json: PlanResource.new(Plan.ordered_by_display_index).serialize
  end
end
```

## Expected behavior
price shows as 2 decimal places.

## Actual behavior
price shows as a string.

## Environment
- Ruby version: 3.2.2
- Rails version: 7.0.3

**Comment by okuramasafumi** [comment]
@remy727 Could you share the schema of `Plan` model?

**Comment by remy727** [comment]
Sure.
```rb
class CreatePlans < ActiveRecord::Migration[7.0]
  def change
    create_table :plans do |t|
      t.string(:name, index: true, null: false)
      t.string(:description)
      t.decimal(:price, default: 0.0, null: false, precision: 10, scale: 2)

      t.timestamps
    end
  end
end
```

**Comment by okuramasafumi** [comment]
How did you get `price` as a string? Is it something like `"0.1e1"?

**Comment by remy727** [comment]
I got `"9.9"` on FrontEnd.

**Comment by okuramasafumi** [comment]
I couldn't reproduce it, could you run `PlanResource.new(Plan.ordered_by_display_index).serialize` in your Rails console and see the output?

**Comment by remy727** [comment]
Sure.

**Comment by remy727** [comment]
```
[1] pry(main)> PlanResource.new(Plan.ordered_by_display_index).serialize
  Plan Load (364.7ms)  SELECT "plans".* FROM "plans" ORDER BY "plans"."display_index" ASC
=> "{\"plans\":[{\"id\":1,\"name\":\"Starter\",\"price\":\"14.9\"},{\"id\":2,\"name\":\"Professional\",\"price\":\"29.9\"},{\"id\":3,\"name\":\"Eye of Sauron\",\"price\":\"99.9\"}]}"
```

**Comment by remy727** [comment]
This is what I get in database.
![image](https://github.com/okuramasafumi/alba/assets/69775411/1ad02bec-cf99-48ab-9f8d-3772017f5983)

**Comment by remy727** [comment]
This is configuration. I hope this helps.
```
# config/initializers/alba.rb

Alba.backend = :oj
Alba.encoder = ->(object) { JSON.generate(object) }
Alba.inflector = :active_support
```

**Comment by remy727** [comment]
Looks like `.round` does not force trailing zeroes.
```rb
[1] pry(main)> 14.9.round(2)
=> 14.9
[2] pry(main)> sprintf('%.2f', 14.9)
=> "14.90"
[3] pry(main)> '%.2f' % 14.9
=> "14.90"
```
I can use `sprintf` or its shorthand `%`

**Comment by okuramasafumi** [comment]
To reproduce this issue, I created a class below:

```ruby
class Plan
  include ActiveModel::Attributes
  attribute :price, :decimal, precision: 10, scale: 2
end
```

And then create an instance.

```ruby
plan = Plan.new
plan.price = 14.90
plan.price.round(2) # => 0.149e2
```

The last line shows it's not `14.9` since it's converted into BigDecimal class that I confirmed in Rails' codebase.

So is your class really having `price` as `decimal` type?

**Comment by remy727** [comment]
Yes. It has.
```
[1] pry(main)> plan = Plan.first
  Plan Load (363.2ms)  SELECT "plans".* FROM "plans" ORDER BY "plans"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> #<Plan:0x000000010be713d0
 id: 1,
 name: "Starter",
 price: 0.149e2,
 created_at: Fri, 01 Sep 2023 07:48:43.392354000 UTC +00:00,
 updated_at: Fri, 01 Sep 2023 07:48:43.392354000 UTC +00:00>
[2] pry(main)> plan.price
=> 0.149e2
[3] pry(main)> plan.price.round(2)
=> 0.149e2
[4] pry(main)> sprintf('%.2f', plan.price)
=> "14.90"
[5] pry(main)>
```

**Comment by okuramasafumi** [comment]
OK, now I found it.

https://discuss.rubyonrails.org/t/bigdecimal-encoded-as-string-in-json/74396/2

The problem seems to be similar as this one. And one of the solutions is to use the library below.

https://github.com/rails/activesupport-json_encoder

`JSON.generate({foo: BigDecimal("1.1")})` outputs string value, not number value. I suspect it's the nature of BigDecimal.

**Comment by remy727** [comment]
Thank you for spending time on this @okuramasafumi
Looks like it's the BigDecimal's issue.
I am going to change `price` field to `price_in_cents` to get integer and play with integer on FrontEnd.

Thank you so much!
