### ISSUE TITLE
Dynamic params

### ISSUE THREAD

**Issue by janklimo** [okuramasafumi/alba#346]
Curious if there is a way to pass in a dynamic param, e.g. an associated record. Params seem to be static-only but please correct me if I misunderstood.

Here's my simplified setup:

```ruby
# Models
class Gallery < ApplicationRecord
  belongs_to :setting,
  has_many :images
end

class Image < ApplicationRecord
  belongs_to :gallery
end

# Serializers
  class GallerySerializer
    include Alba::Resource

    attributes :name

    one :setting, resource: SettingSerializer

    many :images, resource: ImageSerializer #, params: { setting: setting } <~~ this would be handy
  end

  class ImageSerializer
    include Alba::Resource

    attributes :position, :caption, :gallery_id, :url, :alt_text

    attribute :regular_src do |image|
      ImageService
        .new(image, params[:setting]) # <~~ required here
        .regular_src
        .apply_watermark
        .apply_quality
        .apply_format
        .apply_seal
        .to_url
    end

    # ...
  end
```

In summary, galleries belong to a setting and have many images. Every image needs this setting object to build image URLs etc. I'd like to pass this setting object as a param to avoid N+1 when serializing images.

This is possible now like so:

```ruby
GallerySerializer.new(Gallery.last, params: { setting: Gallery.last.setting }).serialize
```

However, I think it would be cleaner if you could add the param in the serializer instead.

**Comment by okuramasafumi** [comment]
Interesting. It's not possible to do so in current API, but if we have something like `dynamic_params` we can do:

```ruby
# many :images, resource: ImageSerializer, params: { setting: setting }
many :images, resource: ImageSerializer ,dynamic_params: do |gallery|
  {setting: gallery.setting}
end
```

This might be useful in some cases.
I'd like to mention that in your case there's no N+1 problem without params since once a gallery is loaded, `image.gallery.setting` fetches data from memory, not DB.

**Comment by janklimo** [comment]
> This might be useful in some cases. I'd like to mention that in your case there's no N+1 problem without params since once a gallery is loaded, `image.gallery.setting` fetches data from memory, not DB.

You're 100% right 👍 forgot I didn't have local caching enabled. Perhaps we can close this for now. Can't think of a very good use case for the new API at this time. Maybe we can revisit if other users have a need for it but I believe it's preferable to keep the API lean unless there is a good reason to expand it.

Thanks for the prompt response!

**Comment by hugopeixoto** [comment]
I was migrating from AMS to alba, and I was using the `include: [associations]` feature. This is where at the render call site, you specify which nested associations you want rendered. I was thinking of emulating this with `params`:

```ruby
class PostSerializer
  include Alba::Resource
  many :comments,
    resource: CommentSerializer,
    if: -> { params.dig(:include, :comments) },
    params: -> { params.merge(include: params.dig(:include, :comments) }
end

class CommentSerializer
  include Alba::Resource
  one :post,
    resource: PostSerializer,
    if: -> { params.dig(:include, :post) },
    params: -> { params.merge(include: params.dig(:include, :post) }
end

# usage
render PostSerializer.new(@post), params: { include: {comments: {}} }
render CommentSerializer.new(@comment), params: { include: {post: {}} }
# ridiculous nested example
render CommentSerializer.new(@comment), params: { include: {post: {comments: {post: {}}}} }
```

Not sure if this is a valid usage for this dynamic params, or if it just should be implemented as a standalone feature (`PostSerializer.new(@post, include: { :comments })`)
