### ISSUE TITLE
Rails compatibility `as_json`

### ISSUE THREAD

**Issue by cgaube** [okuramasafumi/alba#349]
## Describe the bug

Resource `as_json` that is used by rails render: :json  is erroring

```
wrong number of arguments (given 1, expected 0)
```

## To Reproduce

```

user = User.new(1, 'Masafumi OKURA', 'masafumi@example.com')
serializer = UserResource.new(user)

render json: { users: serializer }
```

## Expected behavior

Should work properly 

## Actual behavior
A clear and concise description of what actually happened.

Fatal error

## Environment
- Ruby version: 3.2.2

## Additional context
rails 7.0.8

**Comment by cgaube** [comment]
fix should be something like what was done here 

https://github.com/okuramasafumi/alba/blob/40cbf5f85e88cf12c2bf2dff4140cf4a7bd59956/lib/alba/resource.rb#L63

**Comment by okuramasafumi** [comment]
@cgaube Thank you for reporting, fixed in `fix-as-json-compatibility` branch so you can use it for now. I'll release it as a new version soon!

**Comment by okuramasafumi** [comment]
@cgaube
https://github.com/okuramasafumi/alba/releases/tag/v3.0.3
A new version fixes this bug.
