### ISSUE TITLE
`within` kwarg is ignored for nested associations

### ISSUE THREAD

**Issue by itsthedevman** [okuramasafumi/alba#352]
Greetings! 

## Describe the bug
I am attempting to implement the [JSON:API Resource](https://jsonapi.org/format/#document-resource-objects) object format for two models with circular associations to each other. As I am understanding it, the spec requires associations to be stored in the `"relationships"` key. However, when I replicate this format using Alba, a `SystemStackError` is raised when serializing regardless of restricting the associations using the `within:` kwarg. 

## To Reproduce
1. Load IRB and require "alba"
2. Use the following code to create two "models" and their resources:
#### Models
```rb
class TestUser
  attr_accessor :full_name, :created_at, :company

  def type = "users"
end

class TestCompany
  attr_accessor :name, :created_at, :users

  def type = "companies"
end
```

#### Resources
_For simplicity, I am using `"object_id"` instead of `"id"`_
```rb
class TestUserResource
  include Alba::Resource

  attributes :type, :object_id

  nested_attribute :attributes do
    attributes :full_name, :created_at
  end

  nested_attribute :relationships do
    has_one :company, resource: TestCompanyResource
  end
end

class TestCompanyResource
  include Alba::Resource

  attributes :type, :object_id

  nested_attribute :attributes do
    attributes :name, :created_at
  end

  nested_attribute :relationships do
    has_many :users, resource: TestUserResource
  end
end
```

#### Setup
```rb
company = TestCompany.new.tap do |company|
  company.name = "a_new_company"
  company.created_at = Time.current
end

users = 10.times.map do |index|
  TestUser.new.tap do |user|
    user.full_name = "a_new_user_#{index}"
    user.created_at = Time.current
  end
end

company.users = users
users.each { |u| u.company = company }
```

#### Example usage
```rb
# Example 1
TestCompanyResource.new(company).to_h 

# Example 2
TestCompanyResource.new(company, within: [:users]).to_h

# Example 3
TestCompanyResource.new(company, within: {users: :company}).to_h
```

## Expected behavior
I am expecting:
1. Example 1 to raise `SystemStackError`. 
2. Example 2 to include the `users` association, but each user does not include the `company` association
```json
{
  "type": "companies",
  "object_id": 94400,
  "attributes": {
    "name": "a_new_company",
    "created_at": "date"
  },
  "relationships": {
    "users": [
      {
        "type": "users",
        "object_id": 93640,
        "attributes": {
          "full_name": "a_new_user_0",
          "created_at": "date"
        },
        "relationships": {}
      }
      // the other users
    ]
  }
}
```

3. Example 3 to include the `users` association and each user to include the `company` association
```json
{
  "type": "companies",
  "object_id": 94400,
  "attributes": {
    "name": "a_new_company",
    "created_at": "date"
  },
  "relationships": {
    "users": [
      {
        "type": "users",
        "object_id": 93640,
        "attributes": {
          "full_name": "a_new_user_0",
          "created_at": "date"
        },
        "relationships": {
          "company": {
            "type": "companies",
            "object_id": 94400,
            "attributes": {
              "name": "a_new_company",
              "created_at": "date"
            },
            "relationships": {}
          }
        }
      }
      // the other users
    ]
  }
}
```

## Actual behavior
All three examples receive a `stack level too deep (SystemStackError)`

## Environment
- Ruby version: 3.2.2
- Alba version: 3.0.2

## Additional context
I did some debugging and found this can be resolved by passing the `@within` variable into `NestedAttribute#value`. 

[`Alba::Resource#fetch_attribute:249`](https://github.com/okuramasafumi/alba/blob/40cbf5f85e88cf12c2bf2dff4140cf4a7bd59956/lib/alba/resource.rb#L249)
```rb
when NestedAttribute then attribute.value(object: obj, params: params, within: @within)
```

[`Alba::NestedAttribute#value:15`](https://github.com/okuramasafumi/alba/blob/8ba6cbffe1231a246b628e8b9383445411f97b46/lib/alba/nested_attribute.rb#L15)
```rb
 def value(object:, params:, within:)
```

[`Alba::NestedAttribute#value:19`](https://github.com/okuramasafumi/alba/blob/8ba6cbffe1231a246b628e8b9383445411f97b46/lib/alba/nested_attribute.rb#L19)
```rb
 resource_class.new(object, params: params, within: within).serializable_hash
```

This does resolve the issue I am experiencing but I just started using Alba today so I do not know the repercussions of that change. I was hoping you could help. Please let me know if you need anything else. 

Thank you!

**Comment by okuramasafumi** [comment]
@itsthedevman Thank you for reporting. It's an oversight when I added `nested_attribute` method. And your solution should be correct, so I'm adding your example code to test cases and see if it resolves the issue.

**Comment by okuramasafumi** [comment]
@itsthedevman
https://github.com/okuramasafumi/alba/releases/tag/v3.0.3
A new version fixes this bug.

**Comment by itsthedevman** [comment]
You're awesome. Thank you so much!
