### ISSUE TITLE
Behavior of Custom Metadata is Different to Examples on README

### ISSUE THREAD

**Issue by botamochi0x12** [okuramasafumi/alba#374]
## Abstract

The section "[Metadata](https://github.com/okuramasafumi/alba#metadata)" on `README` likely contains a typo in the metadata key name and the default data.

## To Reproduce

Defines a custom resource class `UserResourceWithDifferentMetaKey` that sets the metadata key to `my_meta` and defaults the metadata content to `{foo: :bar}`.

The following code snippet demonstrates how to reproduce the issue using `irb`:

```ruby
irb(main):001>  require 'alba'
irb(main):002*  class UserResourceWithDifferentMetaKey
irb(main):003*    include Alba::Resource
irb(main):004*  
irb(main):005*    root_key :user, :users
irb(main):006*  
irb(main):007*    attributes :id, :name
irb(main):008*  
irb(main):009*    meta :my_meta do
irb(main):010*      {foo: :bar}
irb(main):011*    end
irb(main):012>  end
irb(main):013*  class User
irb(main):014*    attr_reader :id, :name, :age
irb(main):015*  
irb(main):016*    def initialize(id, name = nil, age = nil)
irb(main):017*      @id = id
irb(main):018*          @name = name
irb(main):019*      @age = age
irb(main):020*    end
irb(main):021>  end
irb(main):022>  user = User.new(1, 'Masafumi OKURA', 'masafumi@example.com')
irb(main):023>  
```

## Expected Behavior

The metadata key should be `meta` (by default), and the content should only include the provided data (`{extra: 42}`). The relevant section of the `README` mentions this behavior.

```ruby
irb(main):024> UserResourceWithDifferentMetaKey.new([user]).serialize(meta: {extra: 42})
irb(main):025>
=> "{\"users\":[{\"id\":1,\"name\":\"Masafumi OKURA\"}],\"meta\":{\"size\":1,\"extra\":42}}"
```

See: https://github.com/okuramasafumi/alba/blob/40077193cbb37a10124ee99ef42eaad9a1166575/README.md?plain=1#L1257-L1258

## Actual Behavior

The metadata key is set to `my_meta`, and the content includes both the provided data (`{extra: 42}`) and the default data (`{foo: "bar"}`).

```ruby
irb(main):024> UserResourceWithDifferentMetaKey.new([user]).serialize(meta: {extra: 42})
irb(main):025>
=> "{\"users\":[{\"id\":1,\"name\":\"Masafumi OKURA\"}],\"my_meta\":{\"foo\":\"bar\",\"extra\":42}}"
```

## Environment

- Ruby version: 3.3.3

## Additional Context

(None)

**Comment by botamochi0x12** [comment]
I'm a big fan of Alba and its ecosystem!
I hope this issue is helpful to you contributors :)

**Comment by okuramasafumi** [comment]
@botamochi0x12 Thank you for pointing out! I think the test in https://github.com/okuramasafumi/alba/blob/main/test/usecases/meta_test.rb#L134-L149 covers this case, so the document is wrong.
Do you want to fix this issue with your Pull Request?

**Comment by botamochi0x12** [comment]
@okuramasafumi

Thanks for your suggestion! I'm happy to create a PR.

While fixing the typo is a good start, I'm concerned we might need another test spec to effectively handle the combination of both metakey alteration and preset meta-content.

Just let me know what you intended for the fix, or whether you'd prefer me to:

1. Add a new test spec that handles this scenario, or
2. Remove the preset meta-content from the document.

I look forward to hearing your thoughts!

**Comment by botamochi0x12** [comment]
Ah, you said

> [...] so the document is wrong.

**Comment by botamochi0x12** [comment]
I'm going to submit a PR soon.

**Comment by botamochi0x12** [comment]
The PR (#375) was merged so I should close this issue soon.
Thanks for your review, @okuramasafumi san :)
