### ISSUE TITLE
Conditional Associations in Alba Trigger SQL Queries Even When Conditions are False

### ISSUE THREAD

**Issue by bbasanta238** [okuramasafumi/alba#377]
## Describe the bug
When serializing a user object with conditional associations using Alba, SQL queries are executed for associations even when the condition for including those associations is set to false.

## To Reproduce

1. Define a `User` model with associations like  `Post`.
2. Define serializers for User, and Post.
4. Fetch a user object with params to exclude association.

``` ruby
class User < ApplicationRecord
  has_many :posts
end

class UserResource
  include Alba::Resource

  attributes :uid, :email

  many :posts, resource: PostResource, if: proc { |_user, _params| params[:include_posts] }
end

class PostResource
  include Alba::Resource

  attributes :uid, :detail
end

UserResource.new(user, params: {  include_posts: false }).to_json
```

## Expected behavior
SQL queries for associations should not be executed when the condition for including those associations is set to false.

## Actual behavior
SQL queries for associations are executed regardless of the conditional inclusion settings.

## Environment
- Ruby version: 3.2.2
- Rails version: 7.0.x
- Alba version: 3.2.0

**Comment by okuramasafumi** [comment]
Thank you for reporting! This seems a bug, I'll investigate it.

**Comment by okuramasafumi** [comment]
@bbasanta238 OK, so the quick fix is to remove the second parameter of the block. As described in https://github.com/okuramasafumi/alba/blob/main/README.md#conditional-attributes, the second parameter is for the attribute, in this case, posts. After removing it, Alba understands the attribute is not necessary.

**Comment by okuramasafumi** [comment]
I added more detailed explanation to README: https://github.com/okuramasafumi/alba?tab=readme-ov-file#caution-for-the-second-parameter-in-if-proc

**Comment by bbasanta238** [comment]
@okuramasafumi Thank you. Removing the second parameter works as expected.  But suppose i need only `uid` and `email`  attribute but it is executing query to select all data. 
``` SQL
SELECT `users`.* FROM `users` ORDER BY `users`.`id` ASC LIMIT 1
``` 

Is it supposed to be like that or it can be optimized?

**Comment by okuramasafumi** [comment]
I'm closing it now since I believe it's resolved.
