### ISSUE TITLE
When typing instance defined attributes, you get a method_missing' error if the passed object does not have that method defined.

### ISSUE THREAD

**Issue by patvice** [okuramasafumi/alba#389]
## Describe the bug

Typing attributes that are defined on a resource by instance methods doesn't seem supported. This came up when trying to add https://github.com/skryukov/typelizer to our current project.

Ideally, we would be able to support adding types to all attributes, in my case, allowing us to generate the correct type definitions on the other side. 

## To Reproduce
Here is an example:

```ruby
class Admin
  def full_name
    "The Admin's name"
  end
end

class AdminResource
  include Alba::Resource

  attributes full_name: [String, true], message: [String, true]

  def message
    "My message"
  end
end

resource = AdminResource.new(Admin.new)
```
Results in this error: `'method_missing': undefined method 'message' for an instance of Admin`

## Expected behavior
I would have expected the resource to default to call the instance method first before going to the object passed into the resource. I would have expected typing the attribute to change the resource's calling behavior. 

The metadata about the resource is correct when expecting the resource object, but we're unable to serialize the data. (aka call `.to_h` to `.to_json` on the resource object.

## Actual behavior
We get a method missing error on the object passed to the resource object.

## Environment
- Ruby version: 3.3 (but it seems like all versions of Ruby would be affected based on the error)
- present in the latest version of alba: 3.3.2

## Additional context
I'm happy to create a change to solve this issue if you are good with supporting this behavior. 😄

**Comment by patvice** [comment]
Upon some more testing, it seems like instance defined methods on the resource at not used when an attribute is type:

Another Example:

```ruby
class Admin
  def full_name
    "The Admin's name"
  end
  
  def message
    "Original message"
  end
end

class AdminResource
  include Alba::Resource

  attributes full_name: [String, true], message: [String, true]

  def message(object)
    object.message + " from resource"
  end
end

resource = AdminResource.new(Admin.new).to_h

**Comment by okuramasafumi** [comment]
@patvice Thank you for the report. So, the mechanism of "preferring methods defined on resource classes" seems working only for simple attributes and not working for type attributes and conditional attributes.
I recognize this as an issue, but I'm not sure yet about what fix is the cleanest. It'll take some time to come up with good ideas.

**Comment by patvice** [comment]
Thanks for solving this! 😄

**Comment by okuramasafumi** [comment]
@patvice https://rubygems.org/gems/alba/versions/3.3.3 version 3.3.3 will fix this issue so please check it out!
