### ISSUE TITLE
Allow conditionals on attribute

### ISSUE THREAD

**Issue by SathishAchilles** [okuramasafumi/alba#87]
Hi, 

thanks for the hard work on the Gem,
I would like to have the `attribute` accept conditionals to decide if that key could even be rendered. 
Conditional Attributes are supported in `ActiveModel::Serializer` https://github.com/rails-api/active_model_serializers/tree/0-8-stable#attributes 

for example, something like
```
attribute :id
attribute :student_name, unless: proc {|resource| resource.name.nil? }
```

now the resulting hash would be
1. if resource has name 
```
{id: 1, student_name: 'Bob'}
```
2. if resource does have name
```
{id: 1}
```

**Comment by okuramasafumi** [comment]
This is the feature I thought I'd like to implement next.
I wonder if we really need `unless` option though. `if` option do the same thing and in my opinion `if` is more readable than `unless` in general.
What do you think?

**Comment by okuramasafumi** [comment]
After implementing conditional attributes in #88, I realized that we can filter attributes based on Hash, not `if` options, described in https://github.com/okuramasafumi/alba/blob/master/README.md#filtering-attributes
This way is a bit tricky using Proc composition and `if` option looks more intuitive, but works well for some cases (eg. filtering all blank attributes).

**Comment by SathishAchilles** [comment]
> This is the feature I thought I'd like to implement next.
> I wonder if we really need `unless` option though. `if` option do the same thing and in my opinion `if` is more readable than `unless` in general.
> What do you think?

actually, following KISS here, I am happy with any conditional argument be it `if` or `unless` ..

**Comment by SathishAchilles** [comment]
> After implementing conditional attributes in #88, I realized that we can filter attributes based on Hash, not `if` options, described in https://github.com/okuramasafumi/alba/blob/master/README.md#filtering-attributes
> This way is a bit tricky using Proc composition and `if` option looks more intuitive, but works well for some cases (eg. filtering all blank attributes).

using `filtering-attributes` would look clumsy when I would want to have custom logic for different attributes.. but I agree that, it is a well thought approach when we have a universal logic to filter out keys for a resource just like your example.. But not always that is the case..

**Comment by okuramasafumi** [comment]
> using filtering-attributes would look clumsy when I would want to have custom logic for different attributes

True, and it's a procedural approach that is against the declarative philosophy of Alba. So we'll prefer `if` option to overriding `converter` in most cases.

**Comment by okuramasafumi** [comment]
Closed by #88 , thanks @SathishAchilles !

**Comment by SathishAchilles** [comment]
thanks for the quick response .. BTW I would love this https://github.com/okuramasafumi/alba/pull/75

**Comment by SathishAchilles** [comment]
BTW, could you please release this?

**Comment by okuramasafumi** [comment]
> BTW, could you please release this?

I'll release version 1.0 finally in this week!
