### ISSUE TITLE
Conditional Attribute should not call the block on failed conditions

### ISSUE THREAD

**Issue by SathishAchilles** [okuramasafumi/alba#91]
For example, 
```
attribute :id
attribute :name, if: proc { |object, _attr| object.respond_to?(:first_name) } do |object|
  object.first_name
end
```

Here, if we the conditionals fail it still executes the block and causes unexpected behavior
```
"#<NoMethodError: undefined method `last_name' 
```

the only workaround is to repeat the conditional check within the block :(

**Comment by okuramasafumi** [comment]
I see, so you'd like to suppress attribute's body block call when if condition doesn't match.
It's possible by checking the arity of if block. If there's only one parameter it means we DON'T want to call attribute's body block. If there are more than one, it means we want to get the result of the attribute.

**Comment by okuramasafumi** [comment]
#92 will resolve this.
